import {Patient} from "./Patient";
import {PatientManager} from "./PatientManager";
let patientManager= new PatientManager()
let patient1=new Patient("Smith",5)
let patient2=new Patient("Jones",4)
let patient3=new Patient("Fehrenbach",6)
let patient4=new Patient("Brown",1)
let patient5=new Patient("Ingram",1)
patientManager.addPatient(patient1)
patientManager.addPatient(patient2)
patientManager.addPatient(patient3)
patientManager.addPatient(patient4)
patientManager.addPatient(patient5)
patientManager.sortPatientCode()
console.log(`bệnh nhân vào khám`)
console.table(patientManager.healing())
console.log(`danh sách bệnh nhân chờ`)
console.table(patientManager.displayPatientList())
console.log(`các bệnh nhân đã khám`)
console.table(patientManager.healing())
console.log(`danh sánh còn chờ`)
console.table(patientManager.displayPatientList())