"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Patient_1 = require("./Patient");
var PatientManager_1 = require("./PatientManager");
var patientManager = new PatientManager_1.PatientManager();
var patient1 = new Patient_1.Patient("Smith", 5);
var patient2 = new Patient_1.Patient("Jones", 4);
var patient3 = new Patient_1.Patient("Fehrenbach", 6);
var patient4 = new Patient_1.Patient("Brown", 1);
var patient5 = new Patient_1.Patient("Ingram", 1);
patientManager.addPatient(patient1);
patientManager.addPatient(patient2);
patientManager.addPatient(patient3);
patientManager.addPatient(patient4);
patientManager.addPatient(patient5);
patientManager.sortPatientCode();
console.log("b\u1EC7nh nh\u00E2n v\u00E0o kh\u00E1m");
console.table(patientManager.healing());
console.log("danh s\u00E1ch b\u1EC7nh nh\u00E2n ch\u1EDD");
console.table(patientManager.displayPatientList());
console.log("c\u00E1c b\u1EC7nh nh\u00E2n \u0111\u00E3 kh\u00E1m");
console.table(patientManager.healing());
console.log("danh s\u00E1nh c\u00F2n ch\u1EDD");
console.table(patientManager.displayPatientList());
